name: NAMKUNBG BOT TG GPU

on: 
  workflow_dispatch:
    inputs:
      link_iso:
        description: 'dán link iso của ae vô đây'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SETUP SERVER TEST
        run: |
          nvidia-smi
